---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

homebrew_kegs:
  - nodenv/nodenv

# homebrew applications
applications:
  - ag
  # - autojump
  - awscli
  - awsebcli
  - git
  - ctags
  - curl
  - git
  # - go
  # - httpie
  # - hugo
  - kubectl
  - kubernetes-helm
  - openssh
  # - neovim
  - nodenv
  - nodenv-package-json-engine
  - npm
  # - postgres
  # - redis
  - rsync
  # - saltstack
  # - terraform
  - tor
  - tree
  - vim
  - wget
  # - zsh

# homebrew cask applications
cask_applications:
  - 1password
  - adobe-acrobat-reader
  # - alfred
  - caffeine
  - charles
  - cyberduck
  # - emacs
  - expo-xde
  - docker
  - dropbox
  - firefox
  # - garmin-express
  - google-chrome
  - genymotion
  - java
  - java11
  - insomnia
  - istat-menus
  - iterm2
  - ledger-live
  - minikube
  - ngrok
  - postico
  - postman
  - robo-3t
  - sequel-pro
  - sketch
  - skype
  - slack
  - soundcleod
  - spotify
  - sublime-text
  # - steam
  - tableplus
  - telegram
  - tor-browser
  - transmission
  - tunnelblick
  - vagrant
  - videostream
  - virtualbox
  - vlc
  - whatsapp
  - zoomus
